version: "3"

services:

  gateway:
    image: $IMAGE_BASE/gateway
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gateway

  mis-web-mis:
    image: $IMAGE_BASE/mis-web-mis
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mis-web
      args:
        - BASE_PATH=/mis

  mis-web-root:
    image: $IMAGE_BASE/mis-web-root
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mis-web
      args:
        - BASE_PATH=

  portal-web-portal:
    image: $IMAGE_BASE/portal-web-portal
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.portal-web
      args:
        - BASE_PATH=/portal

  portal-web-root:
    image: $IMAGE_BASE/portal-web-root
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.portal-web
      args:
        - BASE_PATH=

  docs:
    image: $IMAGE_BASE/docs
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.docs
      args:
        - BASE_PATH=/docs/

  mis-server:
    image: $IMAGE_BASE/mis-server
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mis-server

  shell-server:
    image: $IMAGE_BASE/shell-server
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.shell-server

  vnc-server:
    image: $IMAGE_BASE/vnc-server
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.vnc-server

  auth:
    image: $IMAGE_BASE/auth
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.auth

  clusterops-slurm:
    image: $IMAGE_BASE/clusterops-slurm
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.clusterops-slurm

