displayName: "hpc01Name"
slurm:
  partitions:
    compute:
      nodes: 3
      mem: 262144
      cores: 32
      gpus: 0
      qos:
        - low
        - normal
        - high
      unit: "cpusAlloc"
      comment: "说明"
    GPU:
      nodes: 1
      mem: 262144
      cores: 48
      gpus: 8
      qos: ["low", "normal", "high"]
      unit: "gpu"
      comment: "说明"
