name: Deploy and Push Containers

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:

    permissions:
      contents: read
      packages: write

    name: Build and Push Containers
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: gateway
            file: gateway
            build_args: ""

          - name: mis-server
            file: mis-server
            build_args: ""

          - name: shell-server
            file: shell-server
            build_args: ""

          - name: vnc-server
            file: vnc-server
            build_args: ""

          - name: auth
            file: auth
            build_args: ""

          - name: clusterops-slurm
            file: clusterops-slurm
            build_args: ""

          - name: mis-web-root
            file: mis-web
            build_args: BASE_PATH=/

          - name: mis-web-mis
            file: mis-web
            build_args: BASE_PATH=/mis

          - name: portal-web-root
            file: portal-web
            build_args: BASE_PATH=/

          - name: portal-web-portal
            file: portal-web
            build_args: BASE_PATH=/portal


    steps:
      - uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: ${{ matrix.build_args }}
          tags: ${{ steps.meta.outputs.tags }}
          file: dockerfiles/Dockerfile.${{ matrix.file }}
          labels: ${{ steps.meta.outputs.labels }}
