name: Build and Archive file-server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Archive file-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build file-server's dependencies
        run: pnpm run --filter file-server^... build

      - name: Test file-server
        working-directory: apps/file-server
        run: pnpm test:ci

      - name: Upload test converage
        uses: codecov/codecov-action@v2
        with:
          files: ./apps/file-server/coverage/test/lcov.info
          flags: unittest
          name: codecov-file-server

      - name: Build file-server
        run: pnpm run --filter file-server build

      - name: Archive file-server
        uses: actions/upload-artifact@v3
        with:
          name: file-server
          path: apps/file-server/build/file-server
